// Central product data for the dynamic product detail page.
// Product names, prices and image paths are taken from the existing category pages.
// Replace only the placeholder fullDescription text when real details are available.

const PRODUCTS_DATA = [
  {"slug":"ajwa-dates","name":"Premium Ajwa Dates","category":"Dates","categorySlug":"dates","price":"৳ 850 / kg","image":"images/dates/ajwa-dates.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Premium Ajwa Dates. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"medjool-dates","name":"Medjool Dates","category":"Dates","categorySlug":"dates","price":"৳ 900 / kg","image":"images/dates/medjool-dates.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Medjool Dates. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"safawi-dates","name":"Safawi Dates","category":"Dates","categorySlug":"dates","price":"৳ 800 / kg","image":"images/dates/safawi-dates.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Safawi Dates. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"date-syrup","name":"Date Syrup","category":"Dates","categorySlug":"dates","price":"৳ 350 / bottle","image":"images/dates/date-syrup.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Date Syrup. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"basmati-rice","name":"Basmati Rice","category":"Dry Food","categorySlug":"dry-food","price":"৳ 850 / kg","image":"images/dry-food/basmati-rice.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Basmati Rice. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"chickpeas","name":"Chickpeas","category":"Dry Food","categorySlug":"dry-food","price":"৳ 900 / kg","image":"images/dry-food/chickpeas.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Chickpeas. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"red-lentils","name":"Red Lentils","category":"Dry Food","categorySlug":"dry-food","price":"৳ 800 / kg","image":"images/dry-food/red-lentils.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Red Lentils. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"roasted-chana","name":"Roasted Chana","category":"Dry Food","categorySlug":"dry-food","price":"৳ 350 / bottle","image":"images/dry-food/roasted-chana.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Roasted Chana. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"beef-cuts","name":"Fresh Beef Cuts","category":"Fresh Meat","categorySlug":"fresh-meat","price":"৳ 850 / kg","image":"images/fresh-meat/beef-cuts.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Fresh Beef Cuts. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"beef-boneless","name":"Beef Boneless","category":"Fresh Meat","categorySlug":"fresh-meat","price":"৳ 900 / kg","image":"images/fresh-meat/beef-boneless.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Beef Boneless. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"beef-curry-cut","name":"Beef Curry Cut","category":"Fresh Meat","categorySlug":"fresh-meat","price":"৳ 800 / kg","image":"images/fresh-meat/beef-curry-cut.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Beef Curry Cut. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"fresh-mutton","name":"Fresh Mutton","category":"Fresh Meat","categorySlug":"fresh-meat","price":"৳ 350 / bottle","image":"images/fresh-meat/fresh-mutton.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Fresh Mutton. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"wild-forest-honey","name":"Wild Forest Honey","category":"Honey","categorySlug":"honey","price":"৳ 850 / kg","image":"images/honey/wild-forest-honey.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Wild Forest Honey. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"black-seed-honey","name":"Black Seed Honey","category":"Honey","categorySlug":"honey","price":"৳ 900 / kg","image":"images/honey/black-seed-honey.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Black Seed Honey. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"litchi-honey","name":"Litchi Honey","category":"Honey","categorySlug":"honey","price":"৳ 800 / kg","image":"images/honey/litchi-honey.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Litchi Honey. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"mustard-flower-honey","name":"Mustard Flower Honey","category":"Honey","categorySlug":"honey","price":"৳ 350 / bottle","image":"images/honey/mustard-flower-honey.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Mustard Flower Honey. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"garlic-honey-mix","name":"Garlic & Honey Mix","category":"Mix Food","categorySlug":"mix-food","price":"৳ 850 / kg","image":"images/mix-food/garlic-honey-mix.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Garlic & Honey Mix. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"honey-nut-mix","name":"Honey Nut Mix","category":"Mix Food","categorySlug":"mix-food","price":"৳ 900 / kg","image":"images/mix-food/honey-nut-mix.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Honey Nut Mix. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"date-nut-mix","name":"Date & Nut Mix","category":"Mix Food","categorySlug":"mix-food","price":"৳ 800 / kg","image":"images/mix-food/date-nut-mix.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Date & Nut Mix. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"dry-fruit-mix","name":"Dry Fruit Mix","category":"Mix Food","categorySlug":"mix-food","price":"৳ 350 / bottle","image":"images/mix-food/dry-fruit-mix.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Dry Fruit Mix. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"mixed-roasted-nuts","name":"Mixed Roasted Nuts","category":"Nuts & Seeds","categorySlug":"nuts-seeds","price":"৳ 850 / kg","image":"images/nuts-seeds/mixed-roasted-nuts.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Mixed Roasted Nuts. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"almonds","name":"Almonds","category":"Nuts & Seeds","categorySlug":"nuts-seeds","price":"৳ 900 / kg","image":"images/nuts-seeds/almonds.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Almonds. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"cashews","name":"Cashews","category":"Nuts & Seeds","categorySlug":"nuts-seeds","price":"৳ 800 / kg","image":"images/nuts-seeds/cashews.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Cashews. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"pumpkin-seeds","name":"Pumpkin Seeds","category":"Nuts & Seeds","categorySlug":"nuts-seeds","price":"৳ 350 / bottle","image":"images/nuts-seeds/pumpkin-seeds.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Pumpkin Seeds. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"house-biryani-masala","name":"House Biryani Masala","category":"Special Masala","categorySlug":"special-masala","price":"৳ 850 / kg","image":"images/special-masala/house-biryani-masala.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for House Biryani Masala. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"beef-masala","name":"Beef Masala","category":"Special Masala","categorySlug":"special-masala","price":"৳ 900 / kg","image":"images/special-masala/beef-masala.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Beef Masala. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"chicken-masala","name":"Chicken Masala","category":"Special Masala","categorySlug":"special-masala","price":"৳ 800 / kg","image":"images/special-masala/chicken-masala.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Chicken Masala. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"fish-masala","name":"Fish Masala","category":"Special Masala","categorySlug":"special-masala","price":"৳ 350 / bottle","image":"images/special-masala/fish-masala.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Fish Masala. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"classic-black-tea","name":"Classic Black Tea","category":"Tea","categorySlug":"tea","price":"৳ 850 / kg","image":"images/tea/classic-black-tea.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Classic Black Tea. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"green-tea","name":"Green Tea","category":"Tea","categorySlug":"tea","price":"৳ 900 / kg","image":"images/tea/green-tea.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Green Tea. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"ginger-tea","name":"Ginger Tea","category":"Tea","categorySlug":"tea","price":"৳ 800 / kg","image":"images/tea/ginger-tea.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Ginger Tea. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."},
  {"slug":"herbal-tea","name":"Herbal Tea","category":"Tea","categorySlug":"tea","price":"৳ 350 / bottle","image":"images/tea/herbal-tea.jpg","shortDescription":"Placeholder one-line product description. Replace with your real product description.","fullDescription":"Placeholder full description for Herbal Tea. Replace this text later with the real product details, sourcing story, usage suggestions, and any other information you want customers to know."}
];
